### ISSUE TITLE
Unable to Connect: - MySQL Client Error: Authentication plugin not supported: caching_sha2_password

### ISSUE THREAD

**Issue by julianoventola** [insinfo/galileo#2]
MySQL Client Error: Authentication plugin not supported: caching_sha2_password

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_mysql: ^3.0.0

I am using dart, not flutter

**Comment by insinfo** [comment]
I will investigate this problem, but so that I can help you, answer some questions.
What version of MySQL database are you using?
MySQL or MariaDB ?
Do you have any small sample projects showing the problem hosted on github for me to test?

**Comment by insinfo** [comment]
Have you tried this?

you can change the encryption of the password like this
ALTER USER 'yourusername'@'localhost' IDENTIFIED WITH mysql_native_password BY 'youpassword';

configure MySQL 8.0 to run in mysql_native_password mode
https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

**Comment by julianoventola** [comment]
I was able to connect, it is working now! I had not done this configuration to run mysql docker

Thanks a lot for the help!

**Comment by insinfo** [comment]
Glad to hear you were able to connect.
